"use client";
import { createSlice } from "@reduxjs/toolkit";

// Define a new slice of state for weather data
export const weatherSlice = createSlice({
  name: "weather",
  initialState: {
    city: "",
    weather: null,
    error: null,
  },
  reducers: {
    // Redux reducers to update the state with new data
    setCity: (state, action) => {
      // update city with the value passed in the action payload
      state.city = action.payload;
    },
    setWeather: (state, action) => {
      // update weather with the data passed in the action payload
      state.weather = action.payload;
    },
    setError: (state, action) => {
      // update error with the value passed in the action payload
      state.error = action.payload;
    },
  },
});

// Export the actions generated by the slice
export const { setCity, setWeather, setError } = weatherSlice.actions;

// Selectors to retrieve data from the state
export const selectCity = (state) => state.weather.city;
export const selectWeather = (state) => state.weather.weather;
export const selectError = (state) => state.weather.error;

// Export the reducer generated by the slice
export default weatherSlice.reducer;
